### ISSUE TITLE
a new mirror for pre-commit

### ISSUE THREAD

**Issue by ammarnajjar** [ammarnajjar/mirrors-wemake-python-styleguide#1]
I made this mirror repo for I wanted to use this hook and I didn't find it elsewhere.
It would be easier for other people to find if it was under the [pre-commit](https://github.com/pre-commit/) umbrella.

@asottile, what do you think?

**Comment by asottile** [comment]
the suggested usage for `flake8` plugins is documented [here](https://gitlab.com/pycqa/flake8/blob/master/docs/source/user/using-hooks.rst) -- notably that you'd:

```yaml
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
        additional_dependencies: [wemake-python-styleguide==...]
```
